# Generated by Django 3.2.7 on 2023-10-24 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('action', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('search_params', models.TextField(blank=True, default=None, null=True)),
                ('app_version', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('device', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('device_model', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('device_ip', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_analytics',
                'ordering': ['id'],
            },
        ),
    ]
