# Generated by Django 3.2.7 on 2023-10-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20231024_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='contact_no',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='contact_no_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_counseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
