# Generated by Django 3.2.7 on 2023-10-24 15:08

import appointmentsapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_code', models.CharField(blank=True, db_index=True, default=appointmentsapp.models.Patient.get_patient_code, max_length=50, null=True, unique=True)),
                ('patient_name', models.CharField(db_index=True, default=None, max_length=300, null=True)),
                ('patient_email', models.CharField(db_index=True, default=None, max_length=300, null=True, unique=True)),
                ('patient_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_patient',
                'ordering': ['-patient_id'],
            },
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('counsellor_id', models.AutoField(primary_key=True, serialize=False)),
                ('counsellor_code', models.CharField(blank=True, db_index=True, default=appointmentsapp.models.Counsellor.get_counsellor_code, max_length=50, null=True, unique=True)),
                ('counsellor_name', models.CharField(db_index=True, default=None, max_length=300, null=True)),
                ('counsellor_email', models.CharField(db_index=True, default=None, max_length=300, null=True, unique=True)),
                ('counsellor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_counsellor',
                'ordering': ['-counsellor_id'],
            },
        ),
    ]
