# Generated by Django 3.2.7 on 2023-10-25 05:14

import appointmentsapp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('counsellor_id', models.AutoField(primary_key=True, serialize=False)),
                ('counsellor_code', models.CharField(blank=True, db_index=True, default=appointmentsapp.models.Counsellor.get_counsellor_code, max_length=50, null=True, unique=True)),
                ('counsellor_name', models.CharField(db_index=True, default=None, max_length=250, null=True)),
                ('counsellor_email', models.CharField(db_index=True, default=None, max_length=250, unique=True)),
                ('counsellor_password', models.CharField(default=None, max_length=15)),
            ],
            options={
                'db_table': 'app_counsellor',
                'ordering': ['-counsellor_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_code', models.CharField(blank=True, db_index=True, default=appointmentsapp.models.Patient.get_patient_code, max_length=50, null=True, unique=True)),
                ('patient_name', models.CharField(db_index=True, default=None, max_length=250, null=True)),
                ('patient_email', models.CharField(db_index=True, default=None, max_length=250, unique=True)),
                ('patient_password', models.CharField(default=None, max_length=15)),
            ],
            options={
                'db_table': 'app_patient',
                'ordering': ['-patient_id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_code', models.CharField(blank=True, db_index=True, default=appointmentsapp.models.Appointment.get_appointment_code, max_length=50, null=True, unique=True)),
                ('appointment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('appointment_counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointmentsapp.counsellor')),
                ('appointment_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointmentsapp.patient')),
            ],
            options={
                'db_table': 'app_appointments',
                'ordering': ['-appointment_id'],
            },
        ),
    ]
