# Generated by Django 3.2.7 on 2023-10-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='counsellor_email',
            field=models.CharField(db_index=True, default=None, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='counsellor_name',
            field=models.CharField(db_index=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_email',
            field=models.CharField(db_index=True, default=None, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(db_index=True, default=None, max_length=250, null=True),
        ),
    ]
