# Generated by Django 3.2.7 on 2023-10-24 15:22

import appointmentsapp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsapp', '0002_auto_20231024_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_code', models.CharField(blank=True, db_index=True, default=appointmentsapp.models.Appointment.get_appointment_code, max_length=50, null=True, unique=True)),
                ('appointment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('appointment_counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointmentsapp.counsellor')),
                ('appointment_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointmentsapp.patient')),
            ],
            options={
                'db_table': 'app_appointments',
                'ordering': ['-appointment_id'],
            },
        ),
    ]
