# Generated by Django 3.2.7 on 2023-10-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsapp', '0002_auto_20231025_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='deleted_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='deleted_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='deleted_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
